language: node_js
node_js:
  - "10"
install:
  - yarn install
script:
  - yarn build
  - yarn test
cache:
  yarn: true
deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master